# Generated by Django 4.1.6 on 2023-07-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('app_date_time', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login')),
            ],
        ),
        migrations.CreateModel(
            name='updation',
            fields=[
                ('updation_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=225)),
                ('result', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.user')),
            ],
        ),
        migrations.CreateModel(
            name='suggested_tratment',
            fields=[
                ('suggested_tratment_id', models.AutoField(primary_key=True, serialize=False)),
                ('provided_by', models.CharField(max_length=225)),
                ('treatment', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login')),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_for', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.user')),
            ],
        ),
        migrations.CreateModel(
            name='psychatrist',
            fields=[
                ('psychatrist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='motivation',
            fields=[
                ('motivation_id', models.AutoField(primary_key=True, serialize=False)),
                ('classes', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='meditation',
            fields=[
                ('meditation_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login')),
            ],
        ),
        migrations.CreateModel(
            name='counsilor',
            fields=[
                ('counsilor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.user'),
        ),
    ]
