# Generated by Django 4.1.6 on 2023-07-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mental.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requests',
            name='appointment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.login'),
        ),
    ]
