# Generated by Django 4.1.6 on 2023-07-11 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0002_appointment_appointment_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggested_tratment',
            name='provided_by',
        ),
        migrations.AddField(
            model_name='suggested_tratment',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mental.appointment'),
            preserve_default=False,
        ),
    ]
