# Generated by Django 4.1.6 on 2023-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0003_remove_suggested_tratment_provided_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='awareness',
            fields=[
                ('awareness_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
            ],
        ),
    ]
