# Generated by Django 3.2.19 on 2023-07-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0006_emotions_ratings_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emotions',
            new_name='emot',
        ),
    ]
