# Generated by Django 3.2.19 on 2023-07-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0009_result_result4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requests',
            new_name='requestz',
        ),
    ]
